ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE conversations ADD COLUMN IF NOT EXISTS distance_km DOUBLE PRECISION;
